# Generated by Django 5.2.4 on 2026-02-04 05:10

import commands.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='Ответы')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название команды')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='Генерируется автоматически', max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало набора')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Конец набора')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('field_type', models.CharField(choices=[('short_text', 'Короткий текст'), ('long_text', 'Длинный текст'), ('number', 'Число'), ('photo', 'Фото'), ('video', 'Видео'), ('select', 'Выбор')], max_length=20, verbose_name='Тип поля')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('order', models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядок')),
                ('options', models.JSONField(blank=True, default=list, help_text='Только для select: список вариантов')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=commands.models.attachment_upload_to, verbose_name='Файл')),
                ('label', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='commands.application', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
            },
        ),
    ]
