# Generated by Django 5.2.4 on 2026-01-26 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название команды')),
                ('slug', models.SlugField(unique=True, verbose_name='URL (slug)')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500, verbose_name='Текст вопроса')),
                ('field_type', models.CharField(choices=[('short_text', 'Короткий текст'), ('long_text', 'Длинный текст'), ('number', 'Число'), ('photo', 'Фото'), ('video', 'Видео'), ('select', 'Выбор (Select)')], max_length=20, verbose_name='Тип ответа')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='commands.command')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
