# Generated by Django 5.2.4 on 2026-02-04 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_commands', to=settings.AUTH_USER_MODEL, verbose_name='Лидер/Куратор команды'),
        ),
        migrations.AddField(
            model_name='application',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='commands.command', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='question',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='commands.command', verbose_name='Команда'),
        ),
    ]
