# Generated by Django 5.1.4 on 2026-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='Генерируется автоматически', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
