# Generated by Django 5.2.4 on 2026-02-11 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commands', '0001_initial'),
        ('directions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_applications', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='commands.application', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='command',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='directions.volunteerdirection', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='command',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_commands', to=settings.AUTH_USER_MODEL, verbose_name='Лидер/Куратор команды'),
        ),
        migrations.AddField(
            model_name='command',
            name='volunteers',
            field=models.ManyToManyField(blank=True, db_table='users_volunteer_commands', related_name='volunteer_commands', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
        migrations.AddField(
            model_name='application',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='commands.command', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='question',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='commands.command', verbose_name='Команда'),
        ),
    ]
