# Generated by Django 5.2.4 on 2026-02-04 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_initial'),
        ('directions', '0002_volunteerdirection_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='directions.volunteerdirection', verbose_name='Направление'),
        ),
    ]
