# Generated by Django 5.2.4 on 2026-02-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='field_type',
            field=models.CharField(choices=[('short_text', 'Короткий текст'), ('long_text', 'Длинный текст'), ('number', 'Число'), ('photo', 'Фото'), ('video', 'Видео'), ('select', 'Выбор направления')], max_length=20, verbose_name='Тип поля'),
        ),
    ]
