# Generated by Django 5.2.4 on 2026-01-26 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_required',
        ),
        migrations.AddField(
            model_name='command',
            name='description',
            field=models.TextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='command',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец набора'),
        ),
        migrations.AddField(
            model_name='command',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало набора'),
        ),
        migrations.AlterField(
            model_name='application',
            name='answers',
            field=models.JSONField(verbose_name='Текстовые ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='field_type',
            field=models.CharField(choices=[('short_text', 'Короткий текст'), ('long_text', 'Длинный текст'), ('number', 'Число'), ('photo', 'Фото'), ('video', 'Видео')], max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='applications/%Y/%m/%d/')),
                ('label', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='commands.application')),
            ],
        ),
    ]
