# Generated by Django 5.1.4 on 2026-02-10 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_command_direction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='volunteer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='command_applications', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
        migrations.AddField(
            model_name='command',
            name='volunteers',
            field=models.ManyToManyField(blank=True, db_table='users_volunteer_commands', related_name='volunteer_commands', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
    ]
