# Generated by Django 5.2.4 on 2026-02-04 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commands', '0001_initial'),
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('volunteer', 'Волонтер'), ('curator', 'Куратор')], max_length=20, unique=True, verbose_name='Роль доступа')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль доступа')),
            ],
            options={
                'verbose_name': 'Настройка доступа бота',
                'verbose_name_plural': 'Настройки доступа бота',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Логин')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('visible_password', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Пароль (видимый)')),
                ('image', models.ImageField(blank=True, upload_to='users/', verbose_name='Фото')),
                ('role', models.CharField(choices=[('volunteer', 'Волонтер'), ('teamlead', 'Тимлидер'), ('curator', 'Куратор'), ('admin', 'Администратор')], default='volunteer', max_length=20, verbose_name='Роль (Статус)')),
                ('point', models.IntegerField(default=0, verbose_name='Баллы')),
                ('yellow_card', models.IntegerField(default=0, verbose_name='Желтые карточки')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Доступ в админку')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('commands', models.ManyToManyField(blank=True, related_name='volunteers', to='commands.command', verbose_name='Команды')),
                ('direction', models.ManyToManyField(blank=True, related_name='volunteers', to='directions.volunteerdirection', verbose_name='Направления')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Волонтер',
                'verbose_name_plural': 'Волонтеры',
            },
        ),
        migrations.CreateModel(
            name='ActivityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Баллы за выполнение')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commands.command', verbose_name='Команда')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directions.volunteerdirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Справочник заданий',
                'verbose_name_plural': 'Справочник заданий',
            },
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Комментарий/Отчет')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.activitytask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Заявка на баллы',
                'verbose_name_plural': 'Заявки на баллы',
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteers_photos/', verbose_name='Фото')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('place_of_study', models.CharField(blank=True, max_length=255, verbose_name='Место учебы/работы')),
                ('choice_motives', models.TextField(blank=True, verbose_name='Мотивы')),
                ('why_volunteer', models.TextField(blank=True, verbose_name='Почему волонтер?')),
                ('volunteer_experience', models.TextField(blank=True, verbose_name='Опыт')),
                ('hobbies_skills', models.TextField(blank=True, verbose_name='Хобби')),
                ('strengths', models.TextField(blank=True, verbose_name='Качества')),
                ('why_choose_you', models.TextField(blank=True, verbose_name='Почему вы?')),
                ('ideas_improvements', models.TextField(blank=True, verbose_name='Идеи')),
                ('expectations', models.TextField(blank=True, verbose_name='Ожидания')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Фидбэк')),
                ('agree_inactivity_removal', models.BooleanField(default=False)),
                ('agree_terms', models.BooleanField(default=False)),
                ('ready_travel', models.BooleanField(default=False)),
                ('attend_meetings', models.BooleanField(default=False)),
                ('weekly_hours', models.CharField(blank=True, max_length=50, verbose_name='Время в неделю')),
                ('status', models.CharField(choices=[('submitted', 'Отправлено'), ('interview', 'На собеседовании'), ('accepted', 'Принят'), ('rejected', 'Отказ')], default='submitted', max_length=20, verbose_name='Статус')),
                ('volunteer_created', models.BooleanField(default=False, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commands', models.ManyToManyField(blank=True, related_name='volunteer_applications', to='commands.command')),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_applications', to='directions.volunteerdirection')),
                ('volunteer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Анкета кандидата',
                'verbose_name_plural': 'Анкеты кандидатов',
            },
        ),
        migrations.CreateModel(
            name='VolunteerArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteers_archive_photos/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('why_volunteer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directions', models.ManyToManyField(blank=True, to='directions.volunteerdirection')),
            ],
            options={
                'verbose_name': 'Архив волонтера',
                'verbose_name_plural': 'Архив волонтеров',
            },
        ),
    ]
