# Generated by Django 5.2.4 on 2026-03-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
