# Generated by Django 5.2.4 on 2026-02-16 10:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_alter_question_field_type'),
        ('directions', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.command', verbose_name='Команда (для тимлида)'),
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directions.volunteerdirection', verbose_name='Направление (для куратора)'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='points_awarded',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Начислено баллов'),
        ),
    ]
