# Generated by Django 5.2.4 on 2026-02-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytask',
            name='direction',
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='command',
            field=models.ForeignKey(blank=True, help_text='Если выбрать команду, задание будет видно ТОЛЬКО участникам этой команды. Если оставить пустым — видно ВСЕМ.', null=True, on_delete=django.db.models.deletion.CASCADE, to='commands.command', verbose_name='Спец. Команда (опционально)'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Баллы за выполнение'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='point',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('teamlead', 'Тимлидер'), ('curator', 'Куратор'), ('president', 'Президент'), ('bailiff_base', 'Пристав (База)'), ('bailiff_activity', 'Пристав (Активности)'), ('equity_officer', 'Эквити-офицер'), ('admin', 'Администратор')], default='volunteer', max_length=20, verbose_name='Роль (Статус)'),
        ),
    ]
