# Generated by Django 5.2.4 on 2026-02-06 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_volunteerdirection_responsible'),
        ('users', '0002_remove_activitytask_direction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='visible_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Пароль (видимый)'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата собрания')),
                ('status', models.CharField(choices=[('present', 'П (Присутствовал)'), ('late', 'Оп (Опоздал)'), ('excused', 'УП (Уважительная причина)'), ('absent', 'Н (Не было)')], max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directions.volunteerdirection', verbose_name='Направление')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер')),
            ],
            options={
                'verbose_name': 'Посещаемость',
                'verbose_name_plural': 'Журнал посещаемости',
                'unique_together': {('volunteer', 'direction', 'date')},
            },
        ),
    ]
