# Generated by Django 5.1.6 on 2025-07-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_volunteer_login_volunteer_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direction',
            options={'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтера', 'verbose_name_plural': 'Волонтеры'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='direction',
            field=models.ManyToManyField(related_name='volunteers', to='users.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/users/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='login',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Фамилия Имя'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='point',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='yellow_card',
            field=models.IntegerField(blank=True, null=True, verbose_name='Желтая карточка'),
        ),
    ]
