# Generated by Django 5.2.4 on 2026-04-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_initial'),
        ('users', '0002_activitysubmission_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_direction_selection_open', models.BooleanField(default=False, verbose_name='Открыт выбор направлений')),
            ],
            options={
                'verbose_name': 'Настройки системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
        migrations.AddField(
            model_name='volunteer',
            name='preferred_directions',
            field=models.ManyToManyField(blank=True, related_name='preferring_volunteers', to='directions.volunteerdirection', verbose_name='Желаемые направления (Выбор)'),
        ),
    ]
