# Generated by Django 5.2.4 on 2026-04-01 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_initial'),
        ('users', '0003_appsettings_volunteer_preferred_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='draft_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_volunteers', to='directions.volunteerdirection'),
        ),
    ]
