# Generated by Django 5.2.4 on 2026-04-01 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_volunteer_draft_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='is_registration_open',
            field=models.BooleanField(default=True, verbose_name='Открыта регистрация'),
        ),
    ]
