# Generated by Django 5.2.4 on 2026-02-06 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_command_direction'),
        ('users', '0004_yellowcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysubmission',
            name='points_awarded',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Заполняется куратором при одобрении. Если оставить пустым, возьмутся баллы из задания.', max_digits=6, null=True, verbose_name='Начислено баллов'),
        ),
        migrations.AddField(
            model_name='activitytask',
            name='is_flexible',
            field=models.BooleanField(default=False, help_text='Если включено, куратор сможет сам вписать количество баллов при одобрении (например, от 3 до 5).', verbose_name='Гибкие баллы'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='command',
            field=models.ForeignKey(blank=True, help_text='Если выбрать команду, задание будет видно ТОЛЬКО участникам этой команды.', null=True, on_delete=django.db.models.deletion.CASCADE, to='commands.command', verbose_name='Спец. Команда (опционально)'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='points',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Баллы (базовые/макс)'),
        ),
    ]
