# Generated by Django 5.1.4 on 2026-02-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0004_application_volunteer_command_volunteers'),
        ('users', '0005_activitysubmission_points_awarded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='commands',
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='commands',
            field=models.ManyToManyField(blank=True, related_name='volunteer_members', to='commands.command'),
        ),
    ]
