# Generated by Django 5.1.6 on 2025-07-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0005_alter_volunteer_options_volunteer_visible_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтера', 'verbose_name_plural': 'Волонтеры'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='volunteers', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='volunteers', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
