# Generated by Django 5.1.6 on 2025-07-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_alter_volunteer_options_volunteer_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, к которым принадлежит пользователь', related_name='volunteers', to='auth.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Права пользователя', related_name='volunteers', to='auth.permission', verbose_name='Права'),
        ),
    ]
