# Generated by Django 5.1.4 on 2026-02-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_volunteer_commands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitytask',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='activitytask',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (EN)'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (RU)'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='is_flexible',
            field=models.BooleanField(default=False, help_text='Если включено, куратор сможет сам вписать количество баллов при одобрении.', verbose_name='Гибкие баллы'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название (RU)'),
        ),
    ]
