# Generated by Django 5.1.4 on 2026-04-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='is_points_submission_open',
            field=models.BooleanField(default=True, verbose_name='Открыта отправка баллов (отчетов)'),
        ),
    ]
