# Generated by Django 5.1.6 on 2025-07-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_volunteer_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={},
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='login',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=128, verbose_name='Хеш пароля'),
        ),
    ]
