# Generated by Django 5.1.4 on 2026-04-04 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_appsettings_is_points_submission_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytask',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Справочник заданий', 'verbose_name_plural': 'Справочник заданий'},
        ),
        migrations.AddField(
            model_name='activitytask',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше задание в списке', verbose_name='Порядок'),
        ),
    ]
