# Generated by Django 5.1.6 on 2025-07-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_volunteer_options_remove_volunteer_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтера', 'verbose_name_plural': 'Волонтеры'},
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='direction',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='users.direction', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='yellow_card',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Желтая карточка'),
        ),
    ]
