# Generated by Django 5.1.4 on 2026-04-10 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_initial'),
        ('directions', '0002_initial'),
        ('users', '0008_alter_activitytask_options_activitytask_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название мини-команды')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_teams', to='commands.command', verbose_name='Общая команда')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mini_teams', to='directions.volunteerdirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Мини-команда',
                'verbose_name_plural': 'Мини-команды',
            },
        ),
        migrations.CreateModel(
            name='MiniTeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Волонтер (обзвонщик)'), ('mini_curator', 'Мини-куратор'), ('basist', 'Базист')], default='member', max_length=20, verbose_name='Роль в мини-команде')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_miniteam_roles', to=settings.AUTH_USER_MODEL)),
                ('miniteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='users.miniteam')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniteam_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Участник мини-команды',
                'verbose_name_plural': 'Участники мини-команд',
                'unique_together': {('miniteam', 'volunteer')},
            },
        ),
        migrations.AddField(
            model_name='miniteam',
            name='members',
            field=models.ManyToManyField(related_name='my_mini_teams', through='users.MiniTeamMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SponsorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=255, verbose_name='Название/Имя спонсора')),
                ('contact_info', models.TextField(verbose_name='Контактные данные (телефон, email, соцсети)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает внимания'), ('review', 'На рассмотрении'), ('agreed', 'Соглашение'), ('rejected', 'Отказ')], default='pending', max_length=20, verbose_name='Вердикт')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий от волонтера')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный за обзвон')),
                ('miniteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='users.miniteam')),
            ],
            options={
                'verbose_name': 'Спонсор / Задача',
                'verbose_name_plural': 'База спонсоров',
                'ordering': ['-created_at'],
            },
        ),
    ]
