# Generated by Django 5.1.4 on 2026-04-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_miniteam_miniteammembership_miniteam_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='point_goal',
            field=models.IntegerField(default=100, help_text='Личная цель волонтера', verbose_name='Цель (баллы)'),
        ),
    ]
