# Generated by Django 5.1.6 on 2025-07-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_volunteer_visible_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='login',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Логин'),
        ),
    ]
