# Generated by Django 5.1.6 on 2025-07-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_volunteer_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram @username'),
        ),
    ]
