# Generated by Django 5.1.6 on 2025-07-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_volunteer_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
