# Generated by Django 5.2.4 on 2025-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_volunteer_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фотография'),
        ),
    ]
