# Generated by Django 5.2.4 on 2025-11-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_volunteer_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Телефон')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteers_photos/', verbose_name='Фото')),
                ('why_volunteer', models.TextField(verbose_name='Почему Вы хотите стать волонтером Interact club of Bishkek?')),
                ('volunteer_experience', models.TextField(verbose_name='Расскажите о Вашем опыте волонтёрства')),
                ('hobbies_skills', models.TextField(verbose_name='Опишите свои увлечения, навыки и хобби')),
                ('strengths', models.TextField(verbose_name='Какие ваши сильные качества помогут Вам при получении позиции волонтёра и почему?')),
                ('why_choose_you', models.TextField(verbose_name='Почему мы должны выбрать именно Вас?')),
                ('agree_inactivity_removal', models.BooleanField(verbose_name='Согласны ли вы с тем, что при недостаточной активности Вас могут удалить из клуба?')),
                ('agree_terms', models.BooleanField(verbose_name='Согласны ли вы с пунктом ❕ о добровольности и отсутствии ответственности клуба?')),
                ('ready_travel', models.BooleanField(verbose_name='Готовы ли Вы ездить в различные места (закуп, развоз продуктов и т.д.)?')),
                ('ideas_improvements', models.TextField(verbose_name='Какие идеи и нововведения вы можете предложить для клуба?')),
                ('expectations', models.TextField(verbose_name='Что вы ожидаете от волонтёрской деятельности?')),
                ('weekly_hours', models.CharField(max_length=50, verbose_name='Сколько времени в неделю Вы сможете уделять работе в клубе?')),
                ('attend_meetings', models.BooleanField(verbose_name='Будете ли присутствовать на каждом собрании по субботам?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('directions', models.ManyToManyField(blank=True, to='users.direction', verbose_name='Направления волонтёрской деятельности')),
            ],
            options={
                'verbose_name': 'Анкета волонтёра',
                'verbose_name_plural': 'Анкеты волонтёров',
            },
        ),
    ]
