# Generated by Django 5.2.4 on 2025-11-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_volunteerapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтёр', 'verbose_name_plural': 'Волонтёры'},
        ),
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'verbose_name': 'Анкета кандидата', 'verbose_name_plural': 'Анкеты кандидатов'},
        ),
        migrations.AddField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('interview', 'На собеседовании'), ('accepted', 'Принят'), ('rejected', 'Отказ')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='volunteer_created',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='agree_inactivity_removal',
            field=models.BooleanField(verbose_name='Согласны с удалением при недостаточной активности?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='agree_terms',
            field=models.BooleanField(verbose_name='Согласны с пунктом ❕ о добровольности и отсутствии ответственности клуба?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='attend_meetings',
            field=models.BooleanField(verbose_name='Будете присутствовать на собраниях?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='directions',
            field=models.ManyToManyField(blank=True, to='users.direction', verbose_name='Выбранные направления'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='expectations',
            field=models.TextField(verbose_name='Ожидания от волонтёрской деятельности'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='ideas_improvements',
            field=models.TextField(verbose_name='Идеи и нововведения для клуба'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='ready_travel',
            field=models.BooleanField(verbose_name='Готовы ездить по разным заданиям?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='strengths',
            field=models.TextField(verbose_name='Ваши сильные качества'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='weekly_hours',
            field=models.CharField(max_length=50, verbose_name='Время в неделю'),
        ),
    ]
