# Generated by Django 5.2.4 on 2025-11-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
        ('projects', '0003_alter_project_direction'),
        ('users', '0018_alter_volunteer_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='direction',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='directions.volunteerdirection', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='directions',
            field=models.ManyToManyField(blank=True, to='directions.volunteerdirection', verbose_name='Выбранные направления'),
        ),
    ]
