# Generated by Django 5.2.4 on 2025-11-06 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_delete_direction_alter_volunteer_direction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='Созданный волонтёр'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='agree_inactivity_removal',
            field=models.BooleanField(verbose_name='Согласны с удалением при низкой активности?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='agree_terms',
            field=models.BooleanField(verbose_name='Согласны с условиями клуба?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='expectations',
            field=models.TextField(verbose_name='Ожидания'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='hobbies_skills',
            field=models.TextField(verbose_name='Навыки и хобби'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='ideas_improvements',
            field=models.TextField(verbose_name='Идеи и улучшения'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='ready_travel',
            field=models.BooleanField(verbose_name='Готовы к выездам?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='strengths',
            field=models.TextField(verbose_name='Сильные качества'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer_experience',
            field=models.TextField(verbose_name='Опыт волонтёрства'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='why_choose_you',
            field=models.TextField(verbose_name='Почему выбрать Вас?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='why_volunteer',
            field=models.TextField(verbose_name='Почему Вы хотите стать волонтером?'),
        ),
    ]
