# Generated by Django 5.2.4 on 2025-11-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_remove_projectdirection_description_and_more'),
        ('users', '0020_volunteerapplication_volunteer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='volunteers_archive_photos/')),
                ('why_volunteer', models.TextField()),
                ('volunteer_experience', models.TextField()),
                ('hobbies_skills', models.TextField()),
                ('strengths', models.TextField()),
                ('why_choose_you', models.TextField()),
                ('weekly_hours', models.CharField(blank=True, max_length=50)),
                ('attend_meetings', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('directions', models.ManyToManyField(blank=True, to='directions.volunteerdirection')),
            ],
            options={
                'verbose_name': 'Архив волонтёра',
                'verbose_name_plural': 'Архив волонтёров',
            },
        ),
    ]
