# Generated by Django 5.2.4 on 2025-11-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_volunteerarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
