# Generated by Django 5.1.4 on 2026-01-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_volunteerapplication_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='choice_motives',
            field=models.TextField(blank=True, verbose_name='Мотивы выбора направлений'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Фидбэк (отзыв об анкете)'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='place_of_study',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место учебы/работы'),
        ),
        migrations.AddField(
            model_name='volunteerarchive',
            name='choice_motives',
            field=models.TextField(blank=True, verbose_name='Мотивы выбора направлений'),
        ),
        migrations.AddField(
            model_name='volunteerarchive',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='volunteerarchive',
            name='place_of_study',
            field=models.CharField(blank=True, max_length=255, verbose_name='Место учебы/работы'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='ideas_improvements',
            field=models.TextField(blank=True, verbose_name='Идеи и улучшения'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='why_choose_you',
            field=models.TextField(blank=True),
        ),
    ]
