# Generated by Django 5.1.4 on 2026-01-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_volunteerapplication_choice_motives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAccessConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('volunteer', 'Волонтер (Только команды)'), ('curator', 'Куратор (Полный доступ)')], max_length=20, unique=True, verbose_name='Роль')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль доступа')),
            ],
            options={
                'verbose_name': 'Доступ бота',
                'verbose_name_plural': 'Доступы бота',
            },
        ),
    ]
