# Generated by Django 5.1.4 on 2026-02-03 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_alter_command_slug'),
        ('directions', '0002_remove_projectdirection_description_and_more'),
        ('users', '0024_botaccessconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтер', 'verbose_name_plural': 'Волонтеры'},
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='board',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='point',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='telegram_username',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='visible_password',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='yellow_card',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='volunteer_created',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='commands',
            field=models.ManyToManyField(blank=True, to='commands.command', verbose_name='Команды'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='directions',
            field=models.ManyToManyField(blank=True, to='directions.volunteerdirection', verbose_name='Направления'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('teamlead', 'Тимлидер'), ('curator', 'Куратор'), ('admin', 'Администратор')], default='volunteer', max_length=20, verbose_name='Статус (Роль)'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='yellow_cards',
            field=models.PositiveIntegerField(default=0, verbose_name='Желтые карточки'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='login',
            field=models.CharField(max_length=100, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('points', models.PositiveIntegerField(verbose_name='Баллы за выполнение')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commands.command', verbose_name='Команда')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directions.volunteerdirection', verbose_name='Направление')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Отчет/Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['curator', 'teamlead', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверяющий (Куратор/Тимлид)')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.activitytask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Заявка на баллы',
                'verbose_name_plural': 'Заявки на баллы',
            },
        ),
    ]
