# Generated by Django 5.1.4 on 2026-02-03 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_remove_projectdirection_description_and_more'),
        ('users', '0025_alter_volunteer_options_remove_volunteer_board_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytask',
            name='command',
        ),
        migrations.RemoveField(
            model_name='activitytask',
            name='direction',
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтёр', 'verbose_name_plural': 'Волонтёры'},
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='commands',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='points',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='role',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='yellow_cards',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='board',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='direction',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='directions.volunteerdirection', verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='point',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram @username'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='visible_password',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Пароль (видимый)'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='yellow_card',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Желтая карточка'),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='volunteer_created',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='login',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='Созданный волонтёр'),
        ),
        migrations.DeleteModel(
            name='ActivitySubmission',
        ),
        migrations.DeleteModel(
            name='ActivityTask',
        ),
    ]
