# Generated by Django 5.1.4 on 2026-02-03 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_alter_command_slug'),
        ('directions', '0002_remove_projectdirection_description_and_more'),
        ('users', '0026_remove_activitytask_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='board',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='telegram_id',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='commands',
            field=models.ManyToManyField(blank=True, to='commands.command', verbose_name='Команды'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('teamlead', 'Тимлидер'), ('curator', 'Куратор'), ('admin', 'Администратор')], default='volunteer', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='point',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='yellow_card',
            field=models.IntegerField(default=0, verbose_name='Желтая карточка'),
        ),
        migrations.CreateModel(
            name='ActivityTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задание')),
                ('points', models.PositiveIntegerField(verbose_name='Баллы за выполнение')),
                ('command', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commands.command', verbose_name='Для команды')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directions.volunteerdirection', verbose_name='Для направления')),
            ],
            options={
                'verbose_name': 'Доступное задание',
                'verbose_name_plural': 'Доступные задания',
            },
        ),
        migrations.CreateModel(
            name='ActivitySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['curator', 'teamlead']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.activitytask')),
            ],
            options={
                'verbose_name': 'Заявка на баллы',
                'verbose_name_plural': 'Заявки на баллы',
            },
        ),
    ]
