# Generated by Django 5.1.4 on 2026-02-03 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_alter_command_slug'),
        ('directions', '0002_remove_projectdirection_description_and_more'),
        ('users', '0027_remove_volunteer_board_remove_volunteer_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitysubmission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='activitytask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='botaccessconfig',
            options={},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='volunteerarchive',
            options={},
        ),
        migrations.AddField(
            model_name='activitytask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commands.command', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directions.volunteerdirection', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы за выполнение'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название задания'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to=settings.AUTH_USER_MODEL),
        ),
    ]
