# Generated by Django 5.1.4 on 2026-02-03 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_alter_command_slug'),
        ('directions', '0002_remove_projectdirection_description_and_more'),
        ('users', '0028_alter_activitysubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitysubmission',
            options={'verbose_name': 'Заявка на баллы', 'verbose_name_plural': 'Заявки на баллы'},
        ),
        migrations.AlterModelOptions(
            name='activitytask',
            options={'verbose_name': 'Справочник заданий', 'verbose_name_plural': 'Справочник заданий'},
        ),
        migrations.AlterModelOptions(
            name='botaccessconfig',
            options={'verbose_name': 'Настройка доступа бота', 'verbose_name_plural': 'Настройки доступа бота'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтер', 'verbose_name_plural': 'Волонтеры'},
        ),
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'verbose_name': 'Анкета кандидата', 'verbose_name_plural': 'Анкеты кандидатов'},
        ),
        migrations.AlterModelOptions(
            name='volunteerarchive',
            options={'verbose_name': 'Архив волонтера', 'verbose_name_plural': 'Архив волонтеров'},
        ),
        migrations.RemoveField(
            model_name='volunteerarchive',
            name='attend_meetings',
        ),
        migrations.RemoveField(
            model_name='volunteerarchive',
            name='choice_motives',
        ),
        migrations.RemoveField(
            model_name='volunteerarchive',
            name='hobbies_skills',
        ),
        migrations.RemoveField(
            model_name='volunteerarchive',
            name='place_of_study',
        ),
        migrations.RemoveField(
            model_name='volunteerarchive',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='volunteerarchive',
            name='volunteer_experience',
        ),
        migrations.RemoveField(
            model_name='volunteerarchive',
            name='weekly_hours',
        ),
        migrations.RemoveField(
            model_name='volunteerarchive',
            name='why_choose_you',
        ),
        migrations.AddField(
            model_name='activitysubmission',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий/Ссылка на результат'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Кто проверял'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принято (Баллы начислены)'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.activitytask', verbose_name='Выполненное задание'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Волонтер'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commands.command', verbose_name='Для команды'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание (что нужно сделать)'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directions.volunteerdirection', verbose_name='Для направления'),
        ),
        migrations.AlterField(
            model_name='botaccessconfig',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер (Только личные команды)'), ('curator', 'Куратор (Управление всеми)')], max_length=20, unique=True, verbose_name='Роль доступа'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='commands',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='commands.command', verbose_name='Команды'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='direction',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='directions.volunteerdirection', verbose_name='Направления'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Доступ в админку'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('teamlead', 'Тимлидер'), ('curator', 'Куратор'), ('admin', 'Администратор')], default='volunteer', max_length=20, verbose_name='Роль (Статус)'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='yellow_card',
            field=models.IntegerField(default=0, verbose_name='Желтые карточки'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='agree_inactivity_removal',
            field=models.BooleanField(default=False, verbose_name='Согласен с удалением за неактивность'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='agree_terms',
            field=models.BooleanField(default=False, verbose_name='Согласен с условиями'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='attend_meetings',
            field=models.BooleanField(default=False, verbose_name='Будет на собраниях'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Фидбэк по анкете'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='ready_travel',
            field=models.BooleanField(default=False, verbose_name='Готов к выездам'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('interview', 'На собеседовании'), ('accepted', 'Принят'), ('rejected', 'Отказ')], default='submitted', max_length=20, verbose_name='Статус анкеты'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_profile', to=settings.AUTH_USER_MODEL, verbose_name='Связанный аккаунт волонтера'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer_created',
            field=models.BooleanField(default=False, editable=False, verbose_name='Аккаунт создан'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer_experience',
            field=models.TextField(verbose_name='Опыт волонтерства'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='why_choose_you',
            field=models.TextField(verbose_name='Почему выбрать именно его?'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='why_volunteer',
            field=models.TextField(verbose_name='Почему хочет стать волонтером?'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата архивации'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='directions',
            field=models.ManyToManyField(blank=True, to='directions.volunteerdirection', verbose_name='Направления'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='phone_number',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers_archive_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='why_volunteer',
            field=models.TextField(verbose_name='Причина волонтерства'),
        ),
    ]
