# Generated by Django 5.1.4 on 2026-02-03 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_command_leader'),
        ('directions', '0003_volunteerdirection_responsible'),
        ('users', '0029_alter_activitysubmission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubmission',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='activitysubmission',
            name='reviewer',
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Принято'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='activitysubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.activitytask', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commands.command', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='activitytask',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directions.volunteerdirection', verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='botaccessconfig',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('curator', 'Куратор')], max_length=20, unique=True, verbose_name='Роль доступа'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='agree_inactivity_removal',
            field=models.BooleanField(default=False, verbose_name='Согласен с удалением'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Фидбэк'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='ideas_improvements',
            field=models.TextField(blank=True, verbose_name='Идеи'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Отправлено'), ('interview', 'На собеседовании'), ('accepted', 'Принят'), ('rejected', 'Отказ')], default='submitted', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer_created',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='directions',
            field=models.ManyToManyField(blank=True, to='directions.volunteerdirection'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers_archive_photos/'),
        ),
        migrations.AlterField(
            model_name='volunteerarchive',
            name='why_volunteer',
            field=models.TextField(),
        ),
    ]
