# Generated by Django 5.1.4 on 2026-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_remove_activitysubmission_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
