# Generated by Django 5.1.4 on 2026-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_volunteer_phone_number_alter_volunteer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
