# Generated by Django 5.1.4 on 2026-02-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_command_leader'),
        ('users', '0032_volunteer_phone_number_alter_volunteer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='commands',
            field=models.ManyToManyField(blank=True, to='commands.command', verbose_name='Выбранные команды'),
        ),
    ]
