# Generated by Django 5.1.4 on 2026-02-03 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_command_leader'),
        ('directions', '0003_volunteerdirection_responsible'),
        ('users', '0033_volunteerapplication_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_app_direction', to='directions.volunteerdirection'),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='commands',
            field=models.ManyToManyField(blank=True, related_name='volunteer_app_commands', to='commands.command'),
        ),
    ]
