# Generated by Django 5.1.6 on 2025-07-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_volunteerformarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerformarchive',
            name='moved_to',
            field=models.CharField(blank=True, max_length=50, verbose_name='Куда перенесён'),
        ),
    ]
