# Generated by Django 5.2.4 on 2025-10-03 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0016_volunteer_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/', verbose_name='Обложка')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('title', models.TextField(max_length=5000, verbose_name='Описание проекта')),
                ('price', models.CharField(default='Бесплатно', max_length=100, verbose_name='Цена')),
                ('date', models.DateField(default=datetime.date.today)),
                ('directions', models.ManyToManyField(to='users.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
