# Generated by Django 5.2.4 on 2026-02-04 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.IntegerField(verbose_name='Спорт')),
                ('cyber_sport', models.IntegerField(verbose_name='Киберспорт')),
                ('education', models.IntegerField(verbose_name='Образование')),
                ('fundraising', models.IntegerField(verbose_name='Фандрайзинг')),
                ('cultural', models.IntegerField(verbose_name='Культура')),
                ('total_amount', models.IntegerField(verbose_name='Общая сумма')),
            ],
            options={
                'verbose_name': 'Результат года',
                'verbose_name_plural': 'Результаты года',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/', verbose_name='Обложка')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('title', models.TextField(max_length=5000, verbose_name='Описание проекта')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('category', models.CharField(choices=[('sport', 'Спорт'), ('cyber_sport', 'Киберспорт'), ('education', 'Образование'), ('fundraising', 'Фандрайзинг'), ('cultural', 'Культура')], max_length=50, verbose_name='Категория')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер для записи')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('time_start', models.DateTimeField(verbose_name='Время начало')),
                ('time_end', models.DateTimeField(verbose_name='Время конца')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='directions.projectdirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
