# Generated by Django 5.2.4 on 2026-03-05 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(help_text='Например: Сезон 2025-2026', max_length=100, verbose_name='Бейдж (надзаголовок)')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='hero_slides/', verbose_name='Фоновое изображение')),
                ('button_text', models.CharField(default='Подробнее', max_length=50, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(help_text='Можно писать как относительные пути (volunteer.html), так и полные ссылки (https://...)', max_length=255, verbose_name='Ссылка кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Слайд на главной',
                'verbose_name_plural': 'Слайды на главной',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название партнера')),
                ('logo', models.ImageField(upload_to='partners/', verbose_name='Логотип партнера')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на сайт партнера')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='YearResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, unique=True, verbose_name='Год')),
                ('sport', models.IntegerField(verbose_name='Спорт')),
                ('cyber_sport', models.IntegerField(verbose_name='Киберспорт')),
                ('education', models.IntegerField(verbose_name='Образование')),
                ('fundraising', models.IntegerField(verbose_name='Фандрайзинг')),
                ('cultural', models.IntegerField(verbose_name='Культура')),
                ('total_amount', models.IntegerField(verbose_name='Общая сумма')),
            ],
            options={
                'verbose_name': 'Результат года',
                'verbose_name_plural': 'Результаты года',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/', verbose_name='Обложка')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('title', models.TextField(max_length=5000, verbose_name='Описание проекта')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('category', models.CharField(choices=[('sport', 'Спорт'), ('cyber_sport', 'Киберспорт'), ('education', 'Образование'), ('fundraising', 'Фандрайзинг'), ('cultural', 'Культура')], max_length=50, verbose_name='Категория')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Номер для записи')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('time_start', models.DateTimeField(verbose_name='Время начало')),
                ('time_end', models.DateTimeField(verbose_name='Время конца')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='directions.projectdirection', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
