# Generated by Django 5.2.4 on 2025-11-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
    ]
