# Generated by Django 5.1.4 on 2026-04-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
