# Generated by Django 5.2.4 on 2025-11-06 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
        ('projects', '0002_remove_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directions.volunteerdirection', verbose_name='Направление'),
        ),
    ]
