# Generated by Django 5.2.4 on 2025-11-06 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_remove_projectdirection_description_and_more'),
        ('projects', '0003_alter_project_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='directions.projectdirection', verbose_name='Направление'),
        ),
    ]
