# Generated by Django 5.2.4 on 2026-02-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_faq_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='yearresult',
            name='year',
            field=models.IntegerField(default=2026, unique=True, verbose_name='Год'),
        ),
    ]
