# Generated by Django 5.2.4 on 2025-10-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_directions_project_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.IntegerField()),
                ('cyber_sport', models.IntegerField()),
                ('education', models.IntegerField()),
                ('fundraising', models.IntegerField()),
                ('cultural', models.IntegerField()),
                ('total_amount', models.IntegerField()),
            ],
        ),
    ]
