# Generated by Django 5.2.4 on 2025-10-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_yearresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('sport', 'Спорт'), ('cyber_sport', 'Киберспорт'), ('education', 'Образование'), ('fundraising', 'Фандрайзинг'), ('cultural', 'Культура')], default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
