FROM python:3.11-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    libpq-dev \
    libsm6 \
    libxext6 \
    netcat-traditional \
    gosu \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем только uv
RUN pip install --upgrade pip && pip install --no-cache-dir uv

COPY . .