# Generated by Django 5.2.4 on 2025-10-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_price'),
        ('users', '0016_volunteer_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='directions',
        ),
        migrations.AddField(
            model_name='project',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.direction'),
        ),
    ]
