# Generated by Django 5.2.4 on 2025-11-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdirection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='volunteerdirection',
            name='description',
        ),
    ]
