# Generated by Django 5.1.4 on 2026-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_remove_projectdirection_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerChoiceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Выбор подачи команд')),
            ],
            options={
                'verbose_name': 'Выбор команд',
                'verbose_name_plural': 'Выбор команд',
            },
        ),
        migrations.CreateModel(
            name='VolunteerCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Команды')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-слаг')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
