"""
Django settings for interact project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from dotenv import load_dotenv

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

CSRF_TRUSTED_ORIGINS = [
    "https://interact-club.kg",
    "https://www.interact-club.kg",
    "https://volunteer.interact-club.kg",
    "https://api.interact-club.kg",
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")]

FINIK_ENV = os.getenv("FINIK_ENV", "beta") 


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'jazzmin',
    'drf_yasg',

    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',

    'users',
    # 'form',
    'directions',
    'projects',
    'teatre',
    'finik',
    'logs',
    'commands'


]

with open(BASE_DIR / "keys/finik_private.pem", "r") as f:
    FINIK_PRIVATE_PEM = f.read()

with open(BASE_DIR / "keys/finik_public.pem", "r") as f:
    FINIK_PUBLIC_PEM = f.read()

if FINIK_ENV == "prod":
    FINIK_BASE_URL = "https://api.acquiring.averspay.kg"
    FINIK_HOST = "api.acquiring.averspay.kg"
else:
    FINIK_BASE_URL = "https://beta.api.acquiring.averspay.kg"
    FINIK_HOST = "beta.api.acquiring.averspay.kg"

FINIK_API_KEY = os.getenv("FINIK_API_KEY")
FINIK_ACCOUNT_ID = os.getenv("FINIK_ACCOUNT_ID")
FINIK_QR_NAME = os.getenv("FINIK_QR_NAME")
FINIK_REDIRECT_URL = os.getenv("FINIK_REDIRECT_URL")
FINIK_WEBHOOK_URL = os.getenv("FINIK_WEBHOOK_URL")




# settings.py

# settings.py

JAZZMIN_SETTINGS = {
    "site_title": "Interact CRM",
    "site_header": "Управление",
    "site_brand": "Interact CRM",
    "welcome_sign": "Interact Club of Bishkek",
    
    # 🔥 Указываем путь относительно папки static
    "site_logo": "img/logo.png",
    "login_logo": "img/logo.png",
    "site_icon": "img/logo.png", # Это будет favicon в кладке браузера

    "custom_css": "css/admin_dark.css",
    
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "users.Volunteer": "fas fa-user-astronaut",
        "commands.Command": "fas fa-rocket",
        "commands.Application": "fas fa-file-signature",
        "commands.Question": "fas fa-question-circle",
        "directions.VolunteerDirection": "fas fa-map-signs",
        "users.YellowCard": "fas fa-exclamation-triangle",
    },

    "site_logo_classes": "img-circle",
    "order_with_respect_to": ["users", "commands", "directions"],
    "show_ui_builder": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "superhero",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    "logs.middleware.AdminPageLoggingMiddleware",
]

ROOT_URLCONF = 'interact.urls'

CORS_ALLOW_ALL_ORIGINS = False

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    # Аутентификация (КАК мы узнаем пользователя - по токену)
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    
    # Права доступа (КОГО мы пускаем)
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', # <--- ГЛАВНАЯ СТРОКА
    ],
}


SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
}

AUTH_USER_MODEL = 'users.Volunteer'



WSGI_APPLICATION = 'interact.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # Убедитесь, что здесь используются переменные окружения,
        # которые мы определили в .env
        'NAME': os.environ.get('DB_NAME'), 
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),  # <--- Ключевой момент: должно быть 'db'
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Asia/Bishkek'

USE_I18N = True

USE_TZ = True


# ======== EMAIL SETTINGS ========
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'interact.club.kg@gmail.com'  # твоя почта
EMAIL_HOST_PASSWORD = 'jumxjpogwlwzjalx'       # пароль приложения Google
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Куда собирается вся статика при deploy (не трогай, тут все верно)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 🔥 ДОБАВЬ ВОТ ЭТО: Папка, где лежат твои кастомные стили
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
