# Generated by Django 5.2.4 on 2025-09-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['row', 'seat'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='media/tickets/', verbose_name='Билет PDF'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='row',
            field=models.PositiveIntegerField(verbose_name='Ряд'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.PositiveIntegerField(verbose_name='Место'),
        ),
    ]
