# Generated by Django 5.2.4 on 2025-09-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatre', '0002_alter_booking_options_booking_ticket_pdf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['hall_type', 'row', 'seat'], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
        migrations.AddField(
            model_name='booking',
            name='hall_type',
            field=models.CharField(choices=[('parter', 'Партер'), ('amphitheater', 'Амфитеатр')], default='parter', max_length=20, verbose_name='Тип зала'),
        ),
    ]
