# Generated by Django 5.1.6 on 2025-07-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фамилия Имя')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('image', models.ImageField(blank=True, upload_to='media/users/', verbose_name='Фотография')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
            ],
        ),
    ]
