# Generated by Django 5.1.6 on 2025-07-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_mailingpending_volunteerform_telegram_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingpending',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='volunteerform',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='volunteerformarchive',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='mailingpending',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram @username'),
        ),
    ]
