# Generated by Django 5.2.4 on 2025-07-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_mailingpending_telegram_id_volunteerform_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingpending',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='volunteerform',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='volunteerformarchive',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Фотография'),
        ),
    ]
