# Generated by Django 5.2.4 on 2025-07-09 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_textmailing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingpending',
            options={'verbose_name_plural': 'Отбор 2 этапа'},
        ),
        migrations.AlterModelOptions(
            name='textmailing',
            options={'verbose_name': 'Текст', 'verbose_name_plural': 'Текст для 2 этапа'},
        ),
        migrations.AlterModelOptions(
            name='volunteerform',
            options={'verbose_name': 'Форму заявки', 'verbose_name_plural': 'Форма заявки'},
        ),
        migrations.AlterModelOptions(
            name='volunteerformarchive',
            options={'verbose_name_plural': 'Архив заявок'},
        ),
        migrations.AlterModelOptions(
            name='waitinglist',
            options={'verbose_name_plural': 'Отбор 1 этапа'},
        ),
    ]
