# Generated by Django 5.2.4 on 2026-02-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='ID объекта')),
                ('changes', models.TextField(blank=True, null=True, verbose_name='Изменения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-timestamp'],
            },
        ),
    ]
