# Generated by Django 5.2.4 on 2025-11-28 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_adminactionlog_delete_systemlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('create', 'Создание объекта'), ('update', 'Изменение объекта'), ('delete', 'Удаление объекта'), ('admin_action', 'Действие в админке')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('object_id', models.CharField(blank=True, max_length=200)),
                ('object_repr', models.CharField(blank=True, max_length=300)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AdminActionLog',
        ),
    ]
