# Generated by Django 5.2.4 on 2025-11-28 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_systemlog_delete_adminactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Действие')),
                ('model_name', models.CharField(max_length=255, verbose_name='Модель')),
                ('object_id', models.PositiveIntegerField(null=True, verbose_name='ID объекта')),
                ('changes', models.TextField(blank=True, null=True, verbose_name='Изменения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия',
                'verbose_name_plural': 'Логи действий',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
    ]
