# Generated by Django 5.2.4 on 2026-02-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('seat', models.PositiveIntegerField(verbose_name='Место')),
                ('price', models.PositiveIntegerField(default=1000, verbose_name='Цена')),
                ('hall_type', models.CharField(choices=[('parter', 'Партер'), ('amphitheater', 'Амфитеатр')], default='parter', max_length=20, verbose_name='Тип зала')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('ticket_pdf', models.FileField(blank=True, null=True, upload_to='media/tickets/', verbose_name='Билет PDF')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['hall_type', 'row', 'seat'],
            },
        ),
    ]
