# Generated by Django 5.1.6 on 2025-07-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='login',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='password',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='direction',
            field=models.ManyToManyField(related_name='volunteers', to='users.direction'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='yellow_card',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
