# Generated by Django 5.1.6 on 2025-07-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_volunteer_visible_password_volunteer_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='visible_password',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Пароль (видимый)'),
        ),
    ]
