# Generated by Django 5.2.4 on 2025-07-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_volunteer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='board',
            field=models.BooleanField(default=False),
        ),
    ]
